/**
 * Test Workflow Example
 * 
 * This file demonstrates the 4-server workflow:
 * 1. Architect MCP plans the work
 * 2. Credit Optimizer executes autonomously
 * 3. Autonomous Agent generates code (if needed)
 * 4. Robinson's Toolkit provides integrations
 */

/**
 * Hello World function - demonstrates 4-server workflow
 * Generated by: Architect → Credit Optimizer → Autonomous Agent
 */
export function helloWorld(): string {
  return 'Hello, World!';
}

/**
 * Test the hello world function
 */
export function testHelloWorld(): void {
  const result = helloWorld();
  console.log('Test result:', result);

  if (result !== 'Hello, World!') {
    throw new Error(`Test failed! Expected 'Hello, World!' but got '${result}'`);
  }

  console.log('✅ Test passed!');
}

// Run the test
if (require.main === module) {
  testHelloWorld();
}

