/**
 * Upstash (Redis) Tool Definitions
 * Extracted from temp-redis-mcp.ts
 * Total: 80 tools
 */

export const UPSTASH_TOOLS = [
  { name: 'redis_get', description: 'Get value by key from Redis', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key to retrieve" } },
  { name: 'redis_set', description: 'Set a Redis key-value pair with optional TTL', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_delete', description: 'Delete one or more keys from Redis', inputSchema: { type: "object", properties: { keys: { type: "array", items: { type: "string" } },
  { name: 'redis_exists', description: 'Check if key(s) exist in Redis', inputSchema: { type: "object", properties: { keys: { type: "array", items: { type: "string" } },
  { name: 'redis_ttl', description: 'Get TTL (time to live) for a key in seconds', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_expire', description: 'Set expiration time for a key', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_list_keys', description: 'List Redis keys matching a pattern (use * for wildcard)', inputSchema: { type: "object", properties: { pattern: { type: "string", description: "Pattern to match keys (default: *)", default: "*"} },
  { name: 'redis_delete_by_pattern', description: 'Delete all keys matching a pattern (DANGEROUS - use with caution)', inputSchema: { type: "object", properties: { pattern: { type: "string", description: "Pattern to match keys" } },
  { name: 'redis_mget', description: 'Get multiple values by keys', inputSchema: { type: "object", properties: { keys: { type: "array", items: { type: "string" } },
  { name: 'redis_info', description: 'Get Redis server information and statistics', inputSchema: { type: "object", properties: { section: { type: "string", description: "Info section (server, memory, stats, etc.)"} },
  { name: 'redis_dbsize', description: 'Get total number of keys in current database', inputSchema: { type: "object", properties: {} },
  { name: 'redis_memory_usage', description: 'Get memory usage for a specific key', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_list_sessions', description: 'List all active sessions (keys matching session:*)', inputSchema: { type: "object", properties: { tenant_id: { type: "string", description: "Filter by tenant ID (optional)"} },
  { name: 'redis_inspect_session', description: 'Get detailed information about a session', inputSchema: { type: "object", properties: { session_id: { type: "string", description: "Session ID" } },
  { name: 'redis_clear_tenant_cache', description: 'Clear all cache entries for a specific tenant', inputSchema: { type: "object", properties: { tenant_id: { type: "string", description: "Tenant ID" } },
  { name: 'redis_list_rate_limits', description: 'List all rate limit entries', inputSchema: { type: "object", properties: { user_id: { type: "string", description: "Filter by user ID (optional)" } },
  { name: 'redis_current_db', description: 'Show current database context (provider or tenant)', inputSchema: { type: "object", properties: {} },
  { name: 'redis_flush_db', description: 'Clear all keys in current database (DANGEROUS)', inputSchema: { type: "object", properties: { confirm: { type: "boolean", description: "Must be true to confirm flush"} },
  { name: 'redis_incr', description: 'Increment the integer value of a key by 1', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_decr', description: 'Decrement the integer value of a key by 1', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_incrby', description: 'Increment the integer value of a key by a specific amount', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_decrby', description: 'Decrement the integer value of a key by a specific amount', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_append', description: 'Append a value to a key', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_strlen', description: 'Get the length of the value stored in a key', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_hset', description: 'Set field in a hash', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_hget', description: 'Get field value from a hash', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_hgetall', description: 'Get all fields and values from a hash', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_hdel', description: 'Delete one or more hash fields', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_hexists', description: 'Check if a hash field exists', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_hkeys', description: 'Get all field names in a hash', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_hvals', description: 'Get all values in a hash', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_hlen', description: 'Get the number of fields in a hash', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_lpush', description: 'Prepend one or multiple values to a list', inputSchema: { type: "object", properties: { key: { type: "string", description: "List key" } },
  { name: 'redis_rpush', description: 'Append one or multiple values to a list', inputSchema: { type: "object", properties: { key: { type: "string", description: "List key" } },
  { name: 'redis_lpop', description: 'Remove and get the first element in a list', inputSchema: { type: "object", properties: { key: { type: "string", description: "List key" } },
  { name: 'redis_rpop', description: 'Remove and get the last element in a list', inputSchema: { type: "object", properties: { key: { type: "string", description: "List key" } },
  { name: 'redis_lrange', description: 'Get a range of elements from a list', inputSchema: { type: "object", properties: { key: { type: "string", description: "List key" } },
  { name: 'redis_llen', description: 'Get the length of a list', inputSchema: { type: "object", properties: { key: { type: "string", description: "List key" } },
  { name: 'redis_sadd', description: 'Add one or more members to a set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Set key" } },
  { name: 'redis_smembers', description: 'Get all members of a set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Set key" } },
  { name: 'redis_srem', description: 'Remove one or more members from a set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Set key" } },
  { name: 'redis_sismember', description: 'Check if a value is a member of a set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Set key" } },
  { name: 'redis_scard', description: 'Get the number of members in a set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Set key" } },
  { name: 'redis_zadd', description: 'Add one or more members to a sorted set with scores', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_zrange', description: 'Get a range of members from a sorted set by index', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_zrem', description: 'Remove one or more members from a sorted set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_zscore', description: 'Get the score of a member in a sorted set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_zcard', description: 'Get the number of members in a sorted set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_zrank', description: 'Get the rank of a member in a sorted set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_type', description: 'Get the type of a key (string, list, set, zset, hash)', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_rename', description: 'Rename a key', inputSchema: { type: "object", properties: { oldKey: { type: "string", description: "Current key name" } },
  { name: 'redis_persist', description: 'Remove the expiration from a key', inputSchema: { type: "object", properties: { key: { type: "string", description: "Redis key" } },
  { name: 'redis_publish', description: 'Publish a message to a channel', inputSchema: { type: "object", properties: { channel: { type: "string", description: "Channel name" } },
  { name: 'redis_xadd', description: 'Add entry to a stream', inputSchema: { type: "object", properties: { key: { type: "string", description: "Stream key" } },
  { name: 'redis_xread', description: 'Read entries from one or more streams', inputSchema: { type: "object", properties: { streams: { type: "object", description: "Stream keys and IDs" } },
  { name: 'redis_xrange', description: 'Get range of entries from a stream', inputSchema: { type: "object", properties: { key: { type: "string", description: "Stream key" } },
  { name: 'redis_xlen', description: 'Get the length of a stream', inputSchema: { type: "object", properties: { key: { type: "string", description: "Stream key" } },
  { name: 'redis_geoadd', description: 'Add geospatial items (longitude, latitude, member)', inputSchema: { type: "object", properties: { key: { type: "string", description: "Geo key" } },
  { name: 'redis_geodist', description: 'Get distance between two members', inputSchema: { type: "object", properties: { key: { type: "string", description: "Geo key" } },
  { name: 'redis_georadius', description: 'Query members within radius', inputSchema: { type: "object", properties: { key: { type: "string", description: "Geo key" } },
  { name: 'redis_pfadd', description: 'Add elements to HyperLogLog', inputSchema: { type: "object", properties: { key: { type: "string", description: "HyperLogLog key" } },
  { name: 'redis_pfcount', description: 'Get cardinality of HyperLogLog', inputSchema: { type: "object", properties: { keys: { type: "array", description: "HyperLogLog keys" } },
  { name: 'redis_setbit', description: 'Set or clear bit at offset', inputSchema: { type: "object", properties: { key: { type: "string", description: "Key" } },
  { name: 'redis_getbit', description: 'Get bit value at offset', inputSchema: { type: "object", properties: { key: { type: "string", description: "Key" } },
  { name: 'redis_bitcount', description: 'Count set bits in a string', inputSchema: { type: "object", properties: { key: { type: "string", description: "Key" } },
  { name: 'redis_zrangebyscore', description: 'Get members in sorted set by score range', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_zincrby', description: 'Increment score of member in sorted set', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_zcount', description: 'Count members in score range', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_scan', description: 'Incrementally iterate keys', inputSchema: { type: "object", properties: { cursor: { type: "string", description: "Cursor (0 to start)" } },
  { name: 'redis_hscan', description: 'Incrementally iterate hash fields', inputSchema: { type: "object", properties: { key: { type: "string", description: "Hash key" } },
  { name: 'redis_sscan', description: 'Incrementally iterate set members', inputSchema: { type: "object", properties: { key: { type: "string", description: "Set key" } },
  { name: 'redis_zscan', description: 'Incrementally iterate sorted set members', inputSchema: { type: "object", properties: { key: { type: "string", description: "Sorted set key" } },
  { name: 'redis_getrange', description: 'Get substring of string value', inputSchema: { type: "object", properties: { key: { type: "string", description: "Key" } },
  { name: 'redis_setrange', description: 'Overwrite part of string at offset', inputSchema: { type: "object", properties: { key: { type: "string", description: "Key" } },
  { name: 'redis_sinter', description: 'Intersect multiple sets', inputSchema: { type: "object", properties: { keys: { type: "array", description: "Set keys" } },
  { name: 'redis_sunion', description: 'Union multiple sets', inputSchema: { type: "object", properties: { keys: { type: "array", description: "Set keys" } },
  { name: 'redis_sdiff', description: 'Difference of sets', inputSchema: { type: "object", properties: { keys: { type: "array", description: "Set keys" } },
  { name: 'redis_zunionstore', description: 'Union sorted sets and store result', inputSchema: { type: "object", properties: { destination: { type: "string", description: "Destination key" } },
  { name: 'redis_zinterstore', description: 'Intersect sorted sets and store result', inputSchema: { type: "object", properties: { destination: { type: "string", description: "Destination key" } },
  { name: 'redis_linsert', description: 'Insert element before or after pivot in list', inputSchema: { type: "object", properties: { key: { type: "string", description: "List key" } }
];
